import { existsSync, readFileSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import { createInterface } from "node:readline";
import { join } from "node:path";
import { getActiveProfile } from "./profile.ts";

export type NextActionInput = {
  target_version: string;
  issues: string[];
  intent: string;
  created_at: string;
};

export type WizardOptions = {
  stdin: NodeJS.ReadableStream;
  stdout: NodeJS.WritableStream;
  resumeVersion?: string;
};

// --- Validators ---

export function isValidSemver(value: string): boolean {
  return /^v?\d+\.\d+\.\d+$/.test(value.trim());
}

export function isValidLinearId(value: string, teamKey?: string): boolean {
  if (!value.trim()) return true; // empty list is valid
  const pattern = teamKey
    ? new RegExp(`^${teamKey}-\\d+$`, "i")
    : /^[A-Z]+-\d+$/;
  return value
    .split(/[,\s]+/)
    .map((s) => s.trim())
    .filter(Boolean)
    .every((id) => pattern.test(id));
}

export function parseIssueList(raw: string): string[] {
  return raw
    .split(/[,\s]+/)
    .map((s) => s.trim().toUpperCase())
    .filter(Boolean);
}

// --- YAML serialisation ---

export function serializeNextActionYaml(input: NextActionInput): string {
  const issueLines = input.issues.length
    ? input.issues.map((id) => `  - ${id}`).join("\n")
    : "  []";
  return [
    `# next-action — generated by pokit next-action wizard`,
    `target_version: ${input.target_version}`,
    `issues:`,
    issueLines,
    `intent: "${input.intent.replace(/"/g, '\\"')}"`,
    `created_at: ${input.created_at}`,
    "",
  ].join("\n");
}

export function parseNextActionYaml(content: string): NextActionInput | null {
  try {
    const lines = content.split(/\r?\n/);
    const get = (key: string): string | undefined => {
      const line = lines.find((l) => l.startsWith(`${key}:`));
      return line?.slice(key.length + 1).trim().replace(/^"|"$/g, "");
    };
    const targetVersion = get("target_version");
    const intent = get("intent");
    const createdAt = get("created_at") ?? "";
    if (!targetVersion || !intent) return null;

    // parse issues list
    const issueStartIdx = lines.findIndex((l) => l.trim() === "issues:");
    const issues: string[] = [];
    if (issueStartIdx >= 0) {
      for (const line of lines.slice(issueStartIdx + 1)) {
        if (/^\S/.test(line)) break;
        const match = line.match(/^\s*-\s+(.+)$/);
        if (match) issues.push(match[1].trim());
      }
    }
    return { target_version: targetVersion, issues, intent, created_at: createdAt };
  } catch {
    return null;
  }
}

// --- File I/O ---

export async function writeNextAction(input: NextActionInput, rootDir = "."): Promise<string> {
  const profile = getActiveProfile(rootDir);
  const path = join(rootDir, profile.memoryDir, "next-action.yaml");
  await mkdir(join(rootDir, profile.memoryDir), { recursive: true });
  await writeFile(path, serializeNextActionYaml(input), "utf8");
  return path;
}

export function readNextAction(rootDir = "."): NextActionInput | null {
  const profile = getActiveProfile(rootDir);
  const path = join(rootDir, profile.memoryDir, "next-action.yaml");
  if (!existsSync(path)) return null;
  const content = readFileSync(path, "utf8");
  return parseNextActionYaml(content);
}

// --- Interactive wizard ---

async function prompt(rl: ReturnType<typeof createInterface>, question: string): Promise<string> {
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      resolve(answer);
    });
  });
}

export async function runNextActionWizard(opts: WizardOptions): Promise<NextActionInput> {
  const rl = createInterface({ input: opts.stdin, output: opts.stdout, terminal: false });

  const write = (msg: string) => opts.stdout.write(msg);

  write("\n=== POKit Next-Action Wizard ===\n");
  write("다음 Cycle의 행동 계획을 입력합니다. (release 완료 박제)\n\n");

  // Q1: target version
  let targetVersion = "";
  if (opts.resumeVersion) {
    write(`Target version (기본값: ${opts.resumeVersion}): `);
    const input = await prompt(rl, "");
    targetVersion = input.trim() || opts.resumeVersion;
  } else {
    while (!isValidSemver(targetVersion)) {
      targetVersion = await prompt(rl, "1. 다음 target version (semver, 예: v0.16.0): ");
      targetVersion = targetVersion.trim();
      if (!isValidSemver(targetVersion)) {
        write(`  ⚠️  유효하지 않은 semver입니다. "v0.1.0" 형식으로 입력하세요.\n`);
      }
    }
  }

  // Q2: issue IDs
  let issueRaw = "";
  let issueList: string[] = [];
  let issueValid = false;
  while (!issueValid) {
    issueRaw = await prompt(rl, "2. 다음 Cycle 후보 이슈 (예: POKIT-168, POKIT-169 — 없으면 엔터): ");
    issueRaw = issueRaw.trim();
    if (!issueRaw) {
      issueList = [];
      issueValid = true;
    } else if (!isValidLinearId(issueRaw)) {
      write("  ⚠️  유효하지 않은 Linear ID입니다. 예: POKIT-168, ABC-12\n");
    } else {
      issueList = parseIssueList(issueRaw);
      issueValid = true;
    }
  }

  // Q3: intent
  let intent = "";
  while (!intent) {
    intent = await prompt(rl, "3. 다음 Cycle 의도 한 줄 (왜 이걸 하는지): ");
    intent = intent.trim();
    if (!intent) {
      write("  ⚠️  의도는 비워둘 수 없습니다.\n");
    }
  }

  rl.close();

  const input: NextActionInput = {
    target_version: targetVersion,
    issues: issueList,
    intent,
    created_at: new Date().toISOString(),
  };

  return input;
}
